M48
; DRILL file {KiCad (6.99.0-5210-g1b15854da5)} date Mon Feb 20 10:04:10 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-20T10:04:10+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.99.0-5210-g1b15854da5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
%
G90
G05
T1
X4.8Y-3.0
X4.8Y-3.8
X6.3Y-3.0
X6.3Y-3.8
T0
M30
